CREATE USER Admin1 IDENTIFIED BY Admin1;
GRANT CONNECT,RESOURCE,DBA TO Admin1;

-- Otorgar privilegios 
GRANT CREATE SESSION TO Admin1;
GRANT CREATE TABLE TO Admin1;
GRANT CREATE ANY TABLE TO Admin1;
GRANT SELECT ANY TABLE TO Admin1;
GRANT INSERT ANY TABLE TO Admin1;
GRANT UPDATE ANY TABLE TO Admin1;
GRANT DELETE ANY TABLE TO Admin1;
GRANT DROP ANY TABLE TO Admin1;
GRANT ALTER ANY TABLE TO Admin1;
GRANT EXECUTE ANY PROCEDURE TO Admin1;
GRANT CREATE ANY PROCEDURE TO Admin1;
GRANT DROP ANY PROCEDURE TO Admin1;
GRANT ALTER ANY PROCEDURE TO Admin1;




-- Crear la tabla de roles
CREATE TABLE roles (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR2(20) NOT NULL
);

-- Crear la tabla de usuarios

CREATE TABLE usuario (
  id_usuario NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR2(100) NOT NULL,
  apellido VARCHAR2(100) NOT NULL,
  correo VARCHAR2(100) NOT NULL,
  direccion VARCHAR2(2048) NOT NULL,
  username VARCHAR2(50) NOT NULL,
  password VARCHAR2(100) NOT NULL,
  tarjeta VARCHAR2(16) NOT NULL,
  pin VARCHAR2(4) NOT NULL,
  fecha DATE,
  activo NUMBER(1),
  id_rol NUMBER,
  CONSTRAINT fk_usuario_rol FOREIGN KEY (id_rol) REFERENCES roles(id)
);

-- Crear la tabla de categorías

CREATE TABLE categoria (
  id_categoria NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR2(30) NOT NULL,
  tipo VARCHAR2(30) NOT NULL,
  activo NUMBER(1)
);

-- Crear la tabla de productos

CREATE TABLE producto (
  id_producto NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_categoria NUMBER NOT NULL,
  nombre VARCHAR2(1000) NOT NULL,
  descripcion VARCHAR2(1600) NOT NULL,
  precio NUMBER,
  existencias NUMBER,
  ruta_imagen VARCHAR2(2048),
  activo NUMBER(1),
  CONSTRAINT fk_producto_categoria FOREIGN KEY (id_categoria) REFERENCES categoria(id_categoria)
);

-- Crear la tabla de facturas

CREATE TABLE factura (
  id_factura NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_usuario NUMBER NOT NULL,
  fecha DATE,
  total NUMBER,
  estado NUMBER,
  CONSTRAINT fk_factura_usuario FOREIGN KEY (id_usuario) REFERENCES usuario(id_usuario)
);

-- Crear la tabla de ventas

CREATE TABLE venta (
  id_venta NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_factura NUMBER NOT NULL,
  id_producto NUMBER NOT NULL,
  precio NUMBER,
  cantidad NUMBER,
  CONSTRAINT fk_venta_factura FOREIGN KEY (id_factura) REFERENCES factura(id_factura),
  CONSTRAINT fk_venta_producto FOREIGN KEY (id_producto) REFERENCES producto(id_producto)
);


-- Insertar roles
INSERT INTO roles (nombre) VALUES ('ROLE_ADMIN');
INSERT INTO roles (nombre) VALUES ('ROLE_USER');

-- Insertar usuarios
INSERT INTO usuario (nombre, apellido, correo, direccion, username, password, tarjeta, pin, fecha, activo, id_rol) VALUES
('Laura', 'Mariloca', 'Laura@example.com', 'Heredia Centro', 'user_123', '$2a$12$04CrX/liDFv9De2pwewjH.V54GWW.4aa/LrZJwetwXn5otlGFPv7.', '****-1111', '1234', TO_DATE('2030-04-15', 'YYYY-MM-DD'), 1, 2);/*secretpassword*/
INSERT INTO usuario (nombre, apellido, correo, direccion, username, password, tarjeta, pin, fecha, activo, id_rol) VALUES
('Alondra', 'Loriaa', 'alon123@example.com', 'Llanos del Sol', 'user_456', '$2a$12$Iaz69g9rD9tzKO0kaB.V/.UkwIRHMPr9nPU1kCM7jc.9.wkRrx7Yi', '****-2222', '5678', TO_DATE('2028-04-15', 'YYYY-MM-DD'), 1, 2);/*mypassword*/
INSERT INTO usuario (nombre, apellido, correo, direccion, username, password, tarjeta, pin, fecha, activo, id_rol) VALUES
('Carlos', 'Jimenez', 'jimenez@example.com', 'Calle Sánchez', 'user_789', '$2a$12$stCHKC9z1UJs3rDa2kisfucZnHTXruTuNJwsOILv5bzLOMdc9cRkG', '****-3333', '9101', TO_DATE('2029-04-15', 'YYYY-MM-DD'), 1, 2);/*123456*/
INSERT INTO usuario (nombre, apellido, correo, direccion, username, password, tarjeta, pin, fecha, activo, id_rol) VALUES
('Admin', 'Admin', 'admin@example.com', 'La Aurora', 'admin', '$2a$12$mwkEba3Ge19v4g1dIN3pmuT2oDVyd51NWDHpquHq4wdVeesbcVBBC', '****-4444', '1314', TO_DATE('2032-04-15', 'YYYY-MM-DD'), 1, 1);/*adminpassword*/


-- Insertar categorías
INSERT INTO categoria (nombre, tipo, activo) VALUES ('Naruto', 'Anime', 1);
INSERT INTO categoria (nombre, tipo, activo) VALUES ('Dragon Ball', 'Anime', 1);
INSERT INTO categoria (nombre, tipo, activo) VALUES ('One Piece', 'Anime', 1);
INSERT INTO categoria (nombre, tipo, activo) VALUES ('Mario Bros', 'Videojuegos', 1);
INSERT INTO categoria (nombre, tipo, activo) VALUES ('Fnaf', 'Videojuegos', 1);
INSERT INTO categoria (nombre, tipo, activo) VALUES ('Plantas vs Zombies', 'Videojuegos', 1);
INSERT INTO categoria (nombre, tipo, activo) VALUES ('Polar', 'Osos', 1);
INSERT INTO categoria (nombre, tipo, activo) VALUES ('Panda', 'Osos', 1);
INSERT INTO categoria (nombre, tipo, activo) VALUES ('Escandalosos', 'Osos', 1);
INSERT INTO categoria (nombre, tipo, activo) VALUES ('Otros', 'Osos', 1);
INSERT INTO categoria (nombre, tipo, activo) VALUES ('My Melody', 'MyMelody', 1);
INSERT INTO categoria (nombre, tipo, activo) VALUES ('Cinnamoroll', 'MyMelody', 1);
INSERT INTO categoria (nombre, tipo, activo) VALUES ('Kuromi', 'MyMelody', 1);
INSERT INTO categoria (nombre, tipo, activo) VALUES ('Pompompuri', 'MyMelody', 1);
INSERT INTO categoria (nombre, tipo, activo) VALUES ('Hello Kitty', 'MyMelody', 1);



-- Insertar productos

INSERT INTO producto (id_categoria, nombre, descripcion, precio, existencias, ruta_imagen, activo) VALUES (1, 'Peluche Naruto 25cm', 'Muñeco de peluche de Naruto para niños, juguete coleccionable de anime,  regalo de cumpleaños y navidad, 25cm', 18.240, 5, 'https://www.king-jouet.com/fstrz/r/s/images.king-jouet.com/6/gu909093_6.jpg?frz-v=3234', 1);
INSERT INTO producto (id_categoria, nombre, descripcion, precio, existencias, ruta_imagen, activo) VALUES (1, 'Peluche Sasuke 25cm', 'Muñeco de peluche de Sasuke para niños, juguete coleccionable de anime,  regalo de cumpleaños y navidad, 25cm', 18.240, 10, 'https://media.entertainmentearth.com/assets/images/b5b9233b5fbb43e4be9dc40966ef3f80lg.jpg', 1);
INSERT INTO producto (id_categoria, nombre, descripcion, precio, existencias, ruta_imagen, activo) VALUES (1, 'Peluche Kakashi 25cm', 'Muñeco de peluche de Kakashi para niños, juguete coleccionable de anime,  regalo de cumpleaños y navidad, 25cm', 18.240, 3, 'https://www.cadeau-naruto.com/wp-content/uploads/2023/11/peluche-kakashi-hatake.jpg', 1);
INSERT INTO producto (id_categoria, nombre, descripcion, precio, existencias, ruta_imagen, activo) VALUES (1, 'Peluche Sakura', 'Muñeco de peluche de Sakura para niños, regalo de cumpleaños y navidad', 15.300, 15, 'https://i.ebayimg.com/images/g/1egAAOSwJLBiSsBC/s-l1600.jpg', 1);
INSERT INTO producto (id_categoria, nombre, descripcion, precio, existencias, ruta_imagen, activo) VALUES (1, 'Peluche Hinata 25cm', 'Muñeco de peluche de Hinata para niños, juguete coleccionable de anime,  regalo de cumpleaños y navidad', 18.240, 7, 'https://baseec-img-mng.akamaized.net/images/item/origin/b834a5566407f66b1f3dac5aaa258092.jpg?imformat=generic', 1);
INSERT INTO producto (id_categoria, nombre, descripcion, precio, existencias, ruta_imagen, activo) VALUES (2, 'Peluche Goku 25cm', 'Muñeco de peluche de Goku para niños, juguete coleccionable del anime, regalo de cumpleaños y navidad', 18.240, 9, 'https://i.pinimg.com/736x/27/ea/b2/27eab2aa35434a3234acad1356e5d4ef--dragon-ball-z-plushies.jpg', 1);
INSERT INTO producto (id_categoria, nombre, descripcion, precio, existencias, ruta_imagen, activo) VALUES (2, 'Peluche Vegeta 25cm', 'Muñeco de peluche de Vegeta para niños, juguete coleccionable del anime, regalo de cumpleaños y navidad', 15.000, 10, 'https://m.media-amazon.com/images/I/715ommdiKJL._AC_SY606_.jpg', 1);
INSERT INTO producto (id_categoria, nombre, descripcion, precio, existencias, ruta_imagen, activo) VALUES (2, 'Peluche Piccolo 25cm', 'Muñeco de peluche de Vegeta para niños, juguete coleccionable del anime, regalo de cumpleaños y navidad', 20.000, 5, 'https://i5.walmartimages.com/asr/894534e7-9d88-4ecf-a627-0a393d0e3550.4bab59009d7d7bfcc9e4c832d53e56f3.jpeg', 1);
INSERT INTO producto (id_categoria, nombre, descripcion, precio, existencias, ruta_imagen, activo) VALUES (2, 'Peluche Freezer 15cm', 'Muñeco de peluche de Freezer para niños, juguete coleccionable del anime, regalo de cumpleaños y navidad', 17.500, 6, 'https://tiendadfanatic.com/wp-content/uploads/2021/04/Peluche-Freezer-Dragon-Ball-Z-15cm.jpg', 1);
INSERT INTO producto (id_categoria, nombre, descripcion, precio, existencias, ruta_imagen, activo) VALUES (2, 'Peluche Bulma 30cm', 'Muñeco de peluche de Bulma para niños, juguete coleccionable del anime, regalo de cumpleaños y navidad', 22.000, 11, 'https://todomasbarato.es/6458-thickbox_default/peluche-de-bulma-de-dragon-ball-z-30-cm-nuevo-con-etiquetas-chica-madre-goku.jpg', 1);
INSERT INTO producto (id_categoria, nombre, descripcion, precio, existencias, ruta_imagen, activo) VALUES (3, 'Peluche Luffy 20cm', 'Muñeco de peluche de Luffy para niños, juguete coleccionable del anime, regalo de cumpleaños y navidad', 18.240, 20, 'https://www.figurine-discount.com/46208-thickbox_default/one-piece-peluche-luffy-20-cm.jpg', 1);
INSERT INTO producto (id_categoria, nombre, descripcion, precio, existencias, ruta_imagen, activo) VALUES (3, 'Peluche Chopper 25cm', 'Muñeco de peluche de Chopper para niños, juguete coleccionable del anime, regalo de cumpleaños y navidad', 15.000, 11, 'https://www.figurine-discount.com/22042-thickbox_default/one-piece-peluche-chopper-25-cm.jpg', 1);
INSERT INTO producto (id_categoria, nombre, descripcion, precio, existencias, ruta_imagen, activo) VALUES (3, 'Peluche Zoro 25cm', 'Muñeco de peluche de Zoro para niños, juguete coleccionable del anime, regalo de cumpleaños y navidad', 20.000, 24, 'https://okocollection.fr/1038-large_default/one-piece-peluche-sanji.jpg', 1);
INSERT INTO producto (id_categoria, nombre, descripcion, precio, existencias, ruta_imagen, activo) VALUES (3, 'Peluche Sanji 30cm', 'Muñeco de peluche de Sanji para niños, juguete coleccionable del anime, regalo de cumpleaños y navidad', 17.500, 5, 'https://www.cdiscount.com/pdt2/5/8/8/1/550x550/fp3701315823588/rw/peluche-one-piece-sanji-30-cm.jpg', 1);
INSERT INTO producto (id_categoria, nombre, descripcion, precio, existencias, ruta_imagen, activo) VALUES (3, 'Peluche Nami 25cm', 'Muñeco de peluche de Nami para niños, juguete coleccionable del anime, regalo de cumpleaños y navidad', 22.000, 22, 'https://i5.walmartimages.com/seo/Plush-One-Piece-Nami-Soft-Doll-Toys-New-ge52554_e46b501f-1206-4f58-a4b2-a515cb4cc8a6.f8f8237130251aeaff1d19858f142ef7.jpeg?odnHeight=640&odnWidth=640&odnBg=FFFFFF', 1);
INSERT INTO producto (id_categoria, nombre, descripcion, precio, existencias, ruta_imagen, activo) VALUES (4, 'Peluche de hongo', 'Muñeco de peluche de hongo para niños, juguete coleccionable del videojuego, regalo de cumpleaños y navidad, 25cm', 18.240, 2, 'https://trebolmayoreo.com/wp-content/uploads/2022/06/100002001-Peluche-Hongo-verde-grande-fino.jpg', 1);
INSERT INTO producto (id_categoria, nombre, descripcion, precio, existencias, ruta_imagen, activo) VALUES (4, 'Peluche de Luigi', 'Muñeco de peluche de Luigi para niños, juguete coleccionable del videojuego, regalo de cumpleaños y navidad, 25cm', 15.000, 4, 'https://i.pinimg.com/originals/dd/f0/63/ddf0634dc5c6dddbcd979011016b508b.jpg', 1);
INSERT INTO producto (id_categoria, nombre, descripcion, precio, existencias, ruta_imagen, activo) VALUES (4, 'Peluche de Princesa Peach', 'Muñeco de peluche de Princesa Peach para niños, juguete coleccionable del videojuego, regalo de cumpleaños y navidad, 25cm', 10.000, 30, 'https://i.pinimg.com/originals/a1/f3/a8/a1f3a8d70bf1daf7cc9f127ec4283a08.jpg', 1);
INSERT INTO producto (id_categoria, nombre, descripcion, precio, existencias, ruta_imagen, activo) VALUES (4, 'Peluche de Bowser', 'Muñeco de peluche de Bowser para niños, juguete coleccionable del videojuego, regalo de cumpleaños y navidad, 30cm', 17.500, 10, 'https://www.buildabear.cl/wp-content/uploads/2022/02/23566.jpg', 1);
INSERT INTO producto (id_categoria, nombre, descripcion, precio, existencias, ruta_imagen, activo) VALUES (4, 'Peluche de Yoshi', 'Muñeco de peluche de Yoshi para niños, juguete coleccionable del videojuego, regalo de cumpleaños y navidad, 25cm', 22.000, 5, 'https://cdn.idealo.com/folder/Product/203164/8/203164847/s11_produktbild_max/san-ei-super-mario-bros-peluches-yoshi.jpg', 1);
INSERT INTO producto (id_categoria, nombre, descripcion, precio, existencias, ruta_imagen, activo) VALUES (5, 'Peluche de Freddy Fazbear', 'Muñeco de peluche de Freddy Fazbear para niños, juguete coleccionable del videojuego, regalo de cumpleaños y navidad, 20cm', 18.240, 1, 'https://falabella.scene7.com/is/image/FalabellaPE/gsc_119656307_2428722_3?wid=800&hei=800&qlt=70', 1);
INSERT INTO producto (id_categoria, nombre, descripcion, precio, existencias, ruta_imagen, activo) VALUES (5, 'Peluche de Bonnie the Bonnie', 'Muñeco de peluche de Bonnie the Bonnie para niños, juguete coleccionable del videojuego, regalo de cumpleaños y navidad, 20cm', 16.000, 5, 'https://cdnx.jumpseller.com/aratoystore/image/12602876/resize/540/540?1648671306', 1);
INSERT INTO producto (id_categoria, nombre, descripcion, precio, existencias, ruta_imagen, activo) VALUES (5, 'Peluche de Foxy the Pirate Fox', 'Muñeco de peluche de Foxy the Pirate Fox para niños, juguete coleccionable del videojuego, regalo de cumpleaños y navidad, 20cm', 10.000, 5, 'https://http2.mlstatic.com/D_NQ_NP_781779-MLC73509665107_122023-O.webp', 1);
INSERT INTO producto (id_categoria, nombre, descripcion, precio, existencias, ruta_imagen, activo) VALUES (5, 'Peluche de High Score Toy Chica', 'Muñeco de peluche de High Score Toy Chica para niños, juguete coleccionable del videojuego, regalo de cumpleaños y navidad, 20cm', 17.500, 10, 'https://videodis.es/46413-large_default/peluche-five-nights-at-freddy-s-high-score-chica-inverted-18-cm.jpg', 1);
INSERT INTO producto (id_categoria, nombre, descripcion, precio, existencias, ruta_imagen, activo) VALUES (5, 'Peluche de Chica the Chicken', 'Muñeco de peluche de Chica the Chicken para niños, juguete coleccionable del videojuego, regalo de cumpleaños y navidad, 20cm', 20.000, 5, 'https://boomshock.co/cdn/shop/products/IMG-20221014-WA0005.jpg?v=1665780290&width=1946', 1);
INSERT INTO producto (id_categoria, nombre, descripcion, precio, existencias, ruta_imagen, activo) VALUES (6, 'Peluche de Lanzaguisantes', 'Muñeco de peluche de Lanzaguisantes, juguete coleccionable del videojuego, regalo de cumpleaños y navidad, 30cm', 23.000, 8, 'https://i5.walmartimages.com.mx/mg/gm/3pp/asr/f971a2bc-41ca-4594-8acc-c06911c8075c.aa0de9e918f043df7a39763ae8e01b8f.jpeg?odnHeight=612&odnWidth=612&odnBg=FFFFFF', 1);
INSERT INTO producto (id_categoria, nombre, descripcion, precio, existencias, ruta_imagen, activo) VALUES (6, 'Peluche de Zombie', 'Muñeco de peluche de Zombie, juguete coleccionable del videojuego, regalo de cumpleaños y navidad, 30cm', 16.000, 10, 'https://promart.vteximg.com.br/arquivos/ids/384411-1000-1000/46.jpg?v=637127139349830000', 1);
INSERT INTO producto (id_categoria, nombre, descripcion, precio, existencias, ruta_imagen, activo) VALUES (6, 'Peluche de Girasol', 'Muñeco de peluche de Girasol, juguete coleccionable del videojuego, regalo de cumpleaños y navidad, 30cm', 10.000, 3, 'https://ae01.alicdn.com/kf/Hed5f799b4b9b4af79c6e9c0fccb57374Q.jpg_640x640Q90.jpg_.webp', 1);
INSERT INTO producto (id_categoria, nombre, descripcion, precio, existencias, ruta_imagen, activo) VALUES (6, 'Peluche de Cactus', 'Muñeco de peluche de Cactus, juguete coleccionable del videojuego, regalo de cumpleaños y navidad, 30cm', 18.500, 6, 'https://i5.walmartimages.com.mx/mg/gm/3pp/asr/0e016bc4-0e5d-45a2-b784-881b3940eee0.fed2792022692735d3825e84dee08d47.jpeg?odnHeight=612&odnWidth=612&odnBg=FFFFFF', 1);
INSERT INTO producto (id_categoria, nombre, descripcion, precio, existencias, ruta_imagen, activo) VALUES (6, 'Peluche de Jalapeño', 'Muñeco de peluche de Jalapeño, juguete coleccionable del videojuego, regalo de cumpleaños y navidad, 30cm', 21.000, 5, 'https://i5.walmartimages.com.mx/mg/gm/3pp/asr/1a2d85d8-3187-4660-b408-596d3c2a569d.eabb450b9d9854ad38f4be21e574af1c.jpeg?odnHeight=612&odnWidth=612&odnBg=FFFFFF', 1);
INSERT INTO producto (id_categoria, nombre, descripcion, precio, existencias, ruta_imagen, activo) VALUES (11, 'Cinnamoroll con pijama', 'Muñeco de peluche de MyMelody Cinnamoroll con un pijama azul, juguete coleccionable de MyMelody, regalo de cumpleaños y navidad, 20cm', 18.240, 20, 'https://http2.mlstatic.com/D_NQ_NP_880946-MLC69930227264_062023-O.webp', 1);
INSERT INTO producto (id_categoria, nombre, descripcion, precio, existencias, ruta_imagen, activo) VALUES (11, 'Kuromi traje original', 'Muñeco de peluche de MyMelody Kuromi, juguete coleccionable de MyMelody, regalo de cumpleaños y navidad, 15cm', 16.000, 10, 'https://i.pinimg.com/736x/79/6a/a6/796aa657a7f88e9f109b52b94d43af4e.jpg', 1);
INSERT INTO producto (id_categoria, nombre, descripcion, precio, existencias, ruta_imagen, activo) VALUES (11, 'Pompompuri', 'Muñeco de peluche de Pompompuri, juguete coleccionable de Pompompuri, regalo de cumpleaños y navidad, 22cm', 10.000, 21, 'https://th.bing.com/th/id/OIP.5oZXkZBgH9VAhY4uHe8eMwHaHa?rs=1&pid=ImgDetMain', 1);
INSERT INTO producto (id_categoria, nombre, descripcion, precio, existencias, ruta_imagen, activo) VALUES (11, 'Hello Kitty', 'Muñeco de peluche de MyMelody Hello Kitty, juguete coleccionable de Hello Kitty, regalo de cumpleaños y navidad, 22cm', 17.500, 21, 'https://th.bing.com/th/id/R.166a678f1af4a3c72810b601f97886ce?rik=LLnZeAWQaQ3ZDA&pid=ImgRaw&r=0', 1);
INSERT INTO producto (id_categoria, nombre, descripcion, precio, existencias, ruta_imagen, activo) VALUES (11, 'Pompompuri (Gato)', 'Muñeco de peluche de MyMelody Pompompuri con un traje de Gato, juguete coleccionable de Pompompuri, regalo de cumpleaños y navidad, 22cm', 16.500, 21, 'https://i.pinimg.com/736x/10/9d/40/109d407ab6eed35663a8bccfce571613.jpg', 1);
INSERT INTO producto (id_categoria, nombre, descripcion, precio, existencias, ruta_imagen, activo) VALUES (11, 'Cinnamoroll traje GODIVA 2023', 'Muñeco de peluche de MyMelody Cinnamoroll con traje de GODIVA 2023, juguete coleccionable de MyMelody, regalo de cumpleaños y navidad, 22cm', 18.00, 10, 'https://happycruise.jp/wp-content/uploads/2023/01/valentine2023-sanrio-godiva12.jpg', 1);
INSERT INTO producto (id_categoria, nombre, descripcion, precio, existencias, ruta_imagen, activo) VALUES (12, 'Peluche de Cinnamoroll con pijama', 'Muñeco de peluche de Cinnamoroll con un pijama azul, juguete coleccionable de Cinnamoroll, regalo de cumpleaños y navidad, 20cm', 18.240, 20, 'https://http2.mlstatic.com/D_NQ_NP_880946-MLC69930227264_062023-O.webp', 1);
INSERT INTO producto (id_categoria, nombre, descripcion, precio, existencias, ruta_imagen, activo) VALUES (12, 'Peluche de Cinnamoroll original', 'Muñeco de peluche de Cinnamoroll, juguete coleccionable de Cinnamoroll, regalo de cumpleaños y navidad, 11cm', 10.000, 10, 'https://th.bing.com/th/id/OIP._W14G4-swnEg1fJ9fDLuQAHaHY?pid=ImgDet&w=180&h=180&c=7&dpr=1,3', 1);
INSERT INTO producto (id_categoria, nombre, descripcion, precio, existencias, ruta_imagen, activo) VALUES (12, 'Cinnamoroll (Enamorado)', 'Muñeco de peluche de Cinnamoroll con traje azul y destellos en los ojos, juguete coleccionable de Cinnamoroll, regalo de cumpleaños y navidad, 15cm', 18.000, 10, 'https://meccha-japan.com/557634-large_default/plush-cinnamoroll-sanrio-birthday-2024.jpg', 1);
INSERT INTO producto (id_categoria, nombre, descripcion, precio, existencias, ruta_imagen, activo) VALUES (12, 'Peluche de Cinnamoroll (Fresas Season)', 'Muñeco de peluche de Cinnamoroll con traje de colores pasteles y fresas, juguete coleccionable de Cinnamoroll, regalo de cumpleaños y navidad, 20cm', 15.500, 10, 'https://i.ebayimg.com/images/g/hJ8AAOSwprNi731R/s-l1600.png', 1);
INSERT INTO producto (id_categoria, nombre, descripcion, precio, existencias, ruta_imagen, activo) VALUES (12, 'Cinnamoroll 20 Aniversario', 'Muñeco de peluche de Cinnamoroll con traje alusivo al 20 aniversario, juguete coleccionable de Cinnamoroll, regalo de cumpleaños y navidad, 26cm', 18.500, 10, 'https://meccha-japan.com/248937-large_default/peluche-kotekikai-cinnamoroll-20th.jpg', 1);
INSERT INTO producto (id_categoria, nombre, descripcion, precio, existencias, ruta_imagen, activo) VALUES (12, 'Peluche de Cinnamoroll (Traje GODIVA 2023)', 'Muñeco de peluche de Cinnamoroll con traje de GODIVA 2023, juguete coleccionable de MyMelody, regalo de cumpleaños y navidad, 22cm', 18.00, 10, 'https://happycruise.jp/wp-content/uploads/2023/01/valentine2023-sanrio-godiva12.jpg', 1);
INSERT INTO producto (id_categoria, nombre, descripcion, precio, existencias, ruta_imagen, activo) VALUES (13, 'Peluche de Kuromi (Traje lila)', 'Muñeco de peluche de Kuromi con traje color lila y detalles rosita, juguete coleccionable de Kuromi, regalo de cumpleaños y navidad, 22cm', 19.000, 18, 'https://i.etsystatic.com/10186101/r/il/ec4661/3150024846/il_fullxfull.3150024846_khvt.jpg', 1);
INSERT INTO producto (id_categoria, nombre, descripcion, precio, existencias, ruta_imagen, activo) VALUES (13, 'Peluche de Kuromi (Traje original)', 'Muñeco de peluche de Kuromi con su traje original, juguete coleccionable de Kuromi, regalo de cumpleaños y navidad, 22cm', 16.000, 15, 'https://i.pinimg.com/736x/79/6a/a6/796aa657a7f88e9f109b52b94d43af4e.jpg', 1);
INSERT INTO producto (id_categoria, nombre, descripcion, precio, existencias, ruta_imagen, activo) VALUES (13, 'Peluche de Kuromi (Gala Gotica)', 'Muñeco de peluche de Kuromi con un traje de gala negro con rojo y detalle decorativo en su orejita, juguete coleccionable de Kuromi, regalo de cumpleaños y navidad, 22cm', 17.300, 17, 'https://img.shoplineapp.com/media/image_clips/64a4478bb489f20011a75d67/original.jpg?1688487819', 1);
INSERT INTO producto (id_categoria, nombre, descripcion, precio, existencias, ruta_imagen, activo) VALUES (13, 'Peluche de Kuromi (Picnic)', 'Muñeco de peluche de Kuromi con lazo y moño estilo picnic con tonalidades moradas, juguete coleccionable de Kuromi, regalo de cumpleaños y navidad, 22cm', 12.000, 26, 'https://th.bing.com/th/id/R.b5d09fb38dcebd71efaec0182f3610bd?rik=rioDyEn7cNZAEA&riu=http%3a%2f%2fwww.sanrio.com%2fcdn%2fshop%2ffiles%2f877069-Zoom.1_600x.jpg%3fv%3d1692218616&ehk=01QnUNRv0pQAyDFUIbXpvJdoYGTJB5G3ZBavpO1nfSg%3d&risl=&pid=ImgRaw&r=0', 1);
INSERT INTO producto (id_categoria, nombre, descripcion, precio, existencias, ruta_imagen, activo) VALUES (13, 'Peluche de Kuromi (Negro Elegancia)', 'Muñeco de peluche de Kuromi con traje de gala color negro y detalles en el mismo color, juguete coleccionable de Kuromi, regalo de cumpleaños y navidad, 22cm', 16.500, 21, 'https://d2bzx2vuetkzse.cloudfront.net/unshoppable_producs/ad320ac8-4e02-4834-a5fa-6acaf3048f25.jpeg', 1);
INSERT INTO producto (id_categoria, nombre, descripcion, precio, existencias, ruta_imagen, activo) VALUES (13, 'Peluche de Kuromi (Tierna)', 'Muñeco de peluche de Kuromi con un moño color lila y un bolso del mismo color, juguete coleccionable de Kuromi, regalo de cumpleaños y navidad, 22cm', 10.000, 10, 'https://th.bing.com/th/id/R.f7e548194e9cc5f823431ef8301491a5?rik=u%2bb08eKqJVZ2pw&riu=http%3a%2f%2fwww.sanrio.com%2fcdn%2fshop%2fproducts%2f661660-Zoom.1_600x.jpg%3fv%3d1680901226&ehk=5BdcpxbZht1ZsWBiYyuRiTpg78oP%2bwDBBENIiewF%2fHc%3d&risl=&pid=ImgRaw&r=0', 1);
INSERT INTO producto (id_categoria, nombre, descripcion, precio, existencias, ruta_imagen, activo) VALUES (14, 'Peluche de Pompompuri (Panda)', 'Muñeco de peluche de Pompompuri con un traje de Panda, juguete coleccionable de Pompompuri, regalo de cumpleaños y navidad, 22cm', 18.240, 21, 'https://th.bing.com/th/id/R.77e58d40f079820b3022f3392191ae3d?rik=ay8ZiwsCKMsPXQ&pid=ImgRaw&r=0', 1);
INSERT INTO producto (id_categoria, nombre, descripcion, precio, existencias, ruta_imagen, activo) VALUES (14, 'Peluche de Pompompuri (Vaca)', 'Muñeco de peluche de Pompompuri con un traje de Vaca, juguete coleccionable de Pompompuri, regalo de cumpleaños y navidad, 22cm', 16.000, 21, 'https://cdn.shopify.com/s/files/1/0416/8083/0620/products/184420-Zoom.1_1600x.jpg?v=1613076991', 1);
INSERT INTO producto (id_categoria, nombre, descripcion, precio, existencias, ruta_imagen, activo) VALUES (14, 'Peluche de Pompompuri', 'Muñeco de peluche de Pompompuri, juguete coleccionable de Pompompuri, regalo de cumpleaños y navidad, 22cm', 10.000, 21, 'https://th.bing.com/th/id/OIP.5oZXkZBgH9VAhY4uHe8eMwHaHa?rs=1&pid=ImgDetMain', 1);
INSERT INTO producto (id_categoria, nombre, descripcion, precio, existencias, ruta_imagen, activo) VALUES (14, 'Peluche de Pompompuri con una bellota', 'Muñeco de peluche de Pompompuri jugando con una bellota, juguete coleccionable de Pompompuri, regalo de cumpleaños y navidad, 22cm', 17.500, 21, 'https://th.bing.com/th/id/OIP.2-kThkfXmE0rQ-DPqRa_eQHaHa?w=800&h=800&rs=1&pid=ImgDetMain', 1);
INSERT INTO producto (id_categoria, nombre, descripcion, precio, existencias, ruta_imagen, activo) VALUES (14, 'Peluche de Pompompuri (Gato)', 'Muñeco de peluche de Pompompuri con un traje de Gato, juguete coleccionable de Pompompuri, regalo de cumpleaños y navidad, 22cm', 16.500, 21, 'https://i.pinimg.com/736x/10/9d/40/109d407ab6eed35663a8bccfce571613.jpg', 1);
INSERT INTO producto (id_categoria, nombre, descripcion, precio, existencias, ruta_imagen, activo) VALUES (14, 'Peluche de Pompompuri (Scout)', 'Muñeco de peluche de Pompompuri con traje de Scout, juguete coleccionable de Pompompuri, regalo de cumpleaños y navidad, 22cm', 18.000, 21, 'https://th.bing.com/th/id/R.c9bb553143234b49d31424615b68b60a?rik=f5GVfof%2b3tKxsg&pid=ImgRaw&r=0', 1);
INSERT INTO producto (id_categoria, nombre, descripcion, precio, existencias, ruta_imagen, activo) VALUES (15, 'Peluche de Hello Kitty (Chupa Chups)', 'Muñeco de peluche de Hello Kitty con traje de Chupa Chups, juguete coleccionable de Hello Kitty, regalo de cumpleaños y navidad, 22cm', 17.300, 21, 'https://th.bing.com/th/id/OIP.L0PQm5Z_88bufLILyOsaXQHaG3?w=640&h=594&rs=1&pid=ImgDetMain', 1);
INSERT INTO producto (id_categoria, nombre, descripcion, precio, existencias, ruta_imagen, activo) VALUES (15, 'Peluche de Hello Kitty (Traje original)', 'Muñeco de peluche de Hello Kitty con el traje original, juguete coleccionable de Hello Kitty, regalo de cumpleaños y navidad, 22cm', 9.000, 21, 'https://gadgetsin.com/uploads/2010/10/sanrio_dancing_hello_kitty_speaker_1.jpg', 1);
INSERT INTO producto (id_categoria, nombre, descripcion, precio, existencias, ruta_imagen, activo) VALUES (15, 'Peluche de Hello Kitty (Traje original rosado)', 'Muñeco de peluche de Hello Kitty con el traje original version rosado, juguete coleccionable de Hello Kitty, regalo de cumpleaños y navidad, 22cm', 11.000, 21, 'https://meccha-japan.com/195143-large_default/plush-howa-howa-2l-hello-kitty.jpg', 1);
INSERT INTO producto (id_categoria, nombre, descripcion, precio, existencias, ruta_imagen, activo) VALUES (15, 'Peluche de Hello Kitty (Vestido y zapatillas)', 'Muñeco de peluche de Hello Kitty con un vestido rosado y zapatillas moradas, juguete coleccionable de Hello Kitty, regalo de cumpleaños y navidad, 22cm', 17.500, 21, 'https://th.bing.com/th/id/R.166a678f1af4a3c72810b601f97886ce?rik=LLnZeAWQaQ3ZDA&pid=ImgRaw&r=0', 1);
INSERT INTO producto (id_categoria, nombre, descripcion, precio, existencias, ruta_imagen, activo) VALUES (15, 'Peluche de Hello Kitty (Enamorada)', 'Muñeco de peluche de Hello Kitty con vestido rosa y destellos en los ojos, juguete coleccionable de Hello Kitty, regalo de cumpleaños y navidad, 22cm', 16.000, 21, 'https://th.bing.com/th/id/R.d087759c84b570e9264ee0482d1fee10?rik=pmyj40Sx92kNaA&riu=http%3a%2f%2fwww.sanrio.com%2fcdn%2fshop%2ffiles%2fzz-2309756237_KT_--1_2000x.jpg%3fv%3d1695702500&ehk=Ee4jyxm%2bzL4E2GPshJIEOpT9TnadKGQ0HgT3FBd3KrU%3d&risl=&pid=ImgRaw&r=0', 1);
INSERT INTO producto (id_categoria, nombre, descripcion, precio, existencias, ruta_imagen, activo) VALUES (15, 'Peluche de Hello Kitty (Pijama)', 'Muñeco de peluche de Hello Kitty con un pijama rosita, juguete coleccionable de Hello Kitty, regalo de cumpleaños y navidad, 22cm', 10.000, 21, 'https://i.pinimg.com/originals/54/f6/02/54f602190af0d8185043267a21ded238.jpg', 1);
INSERT INTO producto (id_categoria, nombre, descripcion, precio, existencias, ruta_imagen, activo) VALUES (7, 'Peluche de Polar (Normal)', 'Muñeco de peluche de Polar normal, juguete coleccionable de escandalosos , regalo de cumpleaños y navidad, 22cm', 10.000, 9, 'https://media.entertainmentearth.com/assets/images/6227c1ee4dd74cb2ba4323bae9648f0blg.jpg?_gl=1*18p7dfe*_ga*NjQwOTk1MzY1LjE3MTAyMTgxMDE.*_ga_M8MT85W31R*MTcxMzg1NjMzNS4yLjAuMTcxMzg1NjMzNS42MC4wLjA.', 1);
INSERT INTO producto (id_categoria, nombre, descripcion, precio, existencias, ruta_imagen, activo) VALUES (7, 'Peluche de Polar (Cuatro patas)', 'Muñeco de peluche de Polar cuatro patas, juguete coleccionable de escandalosos , regalo de cumpleaños y navidad, 22cm', 10.000, 9, 'https://resources.claroshop.com/medios-plazavip/mkt/5eaaec2ca4dcc_2000003410101-1jpg.jpg?scale=700&qlty=80', 1);
INSERT INTO producto (id_categoria, nombre, descripcion, precio, existencias, ruta_imagen, activo) VALUES (7, 'Peluche de Polar (Cumpleañero)', 'Muñeco de peluche de Polar Cumpleañero, juguete coleccionable de escandalosos , regalo de cumpleaños y navidad, 22cm', 10.000, 9, 'https://miniso-bh.com/wp-content/uploads/2021/05/2010143612105_1.jpg', 1);
INSERT INTO producto (id_categoria, nombre, descripcion, precio, existencias, ruta_imagen, activo) VALUES (8, 'Peluche de Panda (Normal)', 'Muñeco de peluche de Polar Normal, juguete coleccionable de escandalosos , regalo de cumpleaños y navidad, 22cm', 10.000, 9, 'https://f.fcdn.app/imgs/fbe799/www.minisouruguay.com.uy/miniuy/6828/webp/catalogo/694105513216969410551321761/600x600/peluche-sentado-escandalosos-panda.jpg', 1);
INSERT INTO producto (id_categoria, nombre, descripcion, precio, existencias, ruta_imagen, activo) VALUES (8, 'Peluche de Panda (con Suetita)', 'Muñeco de peluche de Polar con Suetita, juguete coleccionable de escandalosos , regalo de cumpleaños y navidad, 22cm', 10.000, 9, 'https://minisope.vtexassets.com/arquivos/ids/233747-1200-1200?v=638167773951970000&width=1200&height=1200&aspect=true', 1);
INSERT INTO producto (id_categoria, nombre, descripcion, precio, existencias, ruta_imagen, activo) VALUES (8, 'Peluche de Panda (con Manzanita)', 'Muñeco de peluche de Polar con Manzanita, juguete coleccionable de escandalosos , regalo de cumpleaños y navidad, 22cm', 10.000, 9, 'https://dojiw2m9tvv09.cloudfront.net/26518/product/X_192135-1600-16009126.jpg?130&time=1713857039', 1);
INSERT INTO producto (id_categoria, nombre, descripcion, precio, existencias, ruta_imagen, activo) VALUES (9, 'Peluches de Escandalosos', 'Muñecos de peluche de escandalosos, juguetes coleccionables de escandalosos , regalo de cumpleaños y navidad, 22cm', 10.000, 9, 'https://http2.mlstatic.com/D_NQ_NP_924964-MLA54979793842_042023-O.webp', 1);
INSERT INTO producto (id_categoria, nombre, descripcion, precio, existencias, ruta_imagen, activo) VALUES (9, 'Peluches de Escandalosos (Apilados)', 'Muñecos de peluche de escandalosos apilados, juguetes coleccionables de escandalosos , regalo de cumpleaños y navidad, 22cm', 10.000, 9, 'https://http2.mlstatic.com/D_NQ_NP_921822-MLM51330080109_082022-O.webp', 1);
INSERT INTO producto (id_categoria, nombre, descripcion, precio, existencias, ruta_imagen, activo) VALUES (9, 'Peluches de Escandalosos (Frutas)', 'Muñecos de peluche de escandalosos frutas, juguetes coleccionables de escandalosos , regalo de cumpleaños y navidad, 22cm', 10.000, 9, 'https://www.peluchesymas.com/wp-content/uploads/2021/05/as.jpg', 1);
INSERT INTO producto (id_categoria, nombre, descripcion, precio, existencias, ruta_imagen, activo) VALUES (10, 'Peluches de Ositos Cariñositos (Gruñosito)', 'Muñeco de peluche de cariñosito, juguetes coleccionables de escandalosos , regalo de cumpleaños y navidad, 22cm', 10.000, 10, 'https://http2.mlstatic.com/D_NQ_NP_873801-MCO44201264752_112020-O.webp', 1);
INSERT INTO producto (id_categoria, nombre, descripcion, precio, existencias, ruta_imagen, activo) VALUES (10, 'Peluches de Ositos Cariñositos (Amorosita)', 'Muñeco de peluche de amorosita, juguetes coleccionables de escandalosos , regalo de cumpleaños y navidad, 22cm', 10.000, 10, 'https://i.pinimg.com/564x/5e/3a/53/5e3a53fd33cf4c8be5c728c8ef8a079b.jpg', 1);
INSERT INTO producto (id_categoria, nombre, descripcion, precio, existencias, ruta_imagen, activo) VALUES (10, 'Peluches de Ositos Cariñositos (Dormilonsito)', 'Muñeco de peluche de dormilonsito, juguetes coleccionables de escandalosos , regalo de cumpleaños y navidad, 22cm', 10.000, 10, 'https://m.media-amazon.com/images/I/71HfOYloy+L.SS700.jpg', 1);

-- Insertar facturas

INSERT INTO factura (id_usuario, fecha, total, estado) VALUES (1, TO_DATE('2022-01-05', 'YYYY-MM-DD'), 211560, 2);
INSERT INTO factura (id_usuario, fecha, total, estado) VALUES (2, TO_DATE('2022-01-07', 'YYYY-MM-DD'), 554340, 2);
INSERT INTO factura (id_usuario, fecha, total, estado) VALUES (3, TO_DATE('2022-01-07', 'YYYY-MM-DD'), 871000, 2);
INSERT INTO factura (id_usuario, fecha, total, estado) VALUES (1, TO_DATE('2022-01-15', 'YYYY-MM-DD'), 244140, 1);
INSERT INTO factura (id_usuario, fecha, total, estado) VALUES (2, TO_DATE('2022-01-17', 'YYYY-MM-DD'), 414800, 1);
INSERT INTO factura (id_usuario, fecha, total, estado) VALUES (3, TO_DATE('2022-01-21', 'YYYY-MM-DD'), 420000, 1);

-- Insertar ventas

INSERT INTO venta (id_factura, id_producto, precio, cantidad) VALUES (1, 5, 45000, 3);
INSERT INTO venta (id_factura, id_producto, precio, cantidad) VALUES (1, 9, 15780, 2);
INSERT INTO venta (id_factura, id_producto, precio, cantidad) VALUES (1, 10, 15000, 3);
INSERT INTO venta (id_factura, id_producto, precio, cantidad) VALUES (2, 5, 45000, 1);
INSERT INTO venta (id_factura, id_producto, precio, cantidad) VALUES (2, 14, 154000, 3);
INSERT INTO venta (id_factura, id_producto, precio, cantidad) VALUES (2, 9, 15780, 3);
INSERT INTO venta (id_factura, id_producto, precio, cantidad) VALUES (3, 14, 154000, 1);
INSERT INTO venta (id_factura, id_producto, precio, cantidad) VALUES (3, 6, 57000, 1);
INSERT INTO venta (id_factura, id_producto, precio, cantidad) VALUES (3, 15, 330000, 2);
INSERT INTO venta (id_factura, id_producto, precio, cantidad) VALUES (1, 6, 57000, 2);
INSERT INTO venta (id_factura, id_producto, precio, cantidad) VALUES (1, 8, 27600, 3);
INSERT INTO venta (id_factura, id_producto, precio, cantidad) VALUES (1, 9, 15780, 3);
INSERT INTO venta (id_factura, id_producto, precio, cantidad) VALUES (2, 8, 27600, 3);
INSERT INTO venta (id_factura, id_producto, precio, cantidad) VALUES (2, 14, 154000, 2);
INSERT INTO venta (id_factura, id_producto, precio, cantidad) VALUES (2, 3, 24000, 1);
INSERT INTO venta (id_factura, id_producto, precio, cantidad) VALUES (3, 15, 330000, 1);
INSERT INTO venta (id_factura, id_producto, precio, cantidad) VALUES (3, 12, 45000, 1);
INSERT INTO venta (id_factura, id_producto, precio, cantidad) VALUES (3, 10, 15000, 3);

//Tabla de auditorias de errores 
CREATE TABLE ERRORES_AUDIT(USUARIO VARCHAR2(50),
                           ORIGEN VARCHAR2(50),
                           FECHA DATE,
                           VERROR VARCHAR2(600)

); 
 
 -- Funcion de traer ventas 
CREATE OR REPLACE FUNCTION GET_VENTAS RETURN SYS_REFCURSOR IS
    resultado SYS_REFCURSOR;
    VCOD NUMBER;
    VMES VARCHAR2(500);
BEGIN
    OPEN resultado FOR SELECT * FROM VENTA;
    RETURN resultado;
    
EXCEPTION    
     WHEN OTHERS THEN  
     VMES := SQLERRM;
     VCOD := SQLCODE;
     INSERT INTO ERRORES_AUDIT VALUES (USER,'GET_VENTAS',SYSDATE, VCOD || ' - '|| VMES );
END GET_VENTAS;

-- Funcion de traer  Categorias impl

CREATE OR REPLACE PROCEDURE GET_CATEGORIAS (
    p_activos IN BOOLEAN,
    p_resultado OUT SYS_REFCURSOR
) IS
    VCOD NUMBER;
    VMES VARCHAR2(500);
BEGIN
    BEGIN
       
        IF p_activos THEN
            OPEN p_resultado FOR
            SELECT * FROM categoria
            WHERE ACTIVO = 1;
        ELSE
            OPEN p_resultado FOR
            SELECT * FROM categoria;
        END IF;
    EXCEPTION
        WHEN OTHERS THEN
            VMES := SQLERRM;
            VCOD := SQLCODE;
            INSERT INTO ERRORES_AUDIT (USUARIO, ORIGEN, FECHA, VERROR)
            VALUES (USER, 'GET_CATEGORIAS', SYSDATE, VCOD || ' - ' || VMES);
            RAISE;--permite que el error que se ha registrado en la tabla ERRORES_AUDIT tambi�n se propague
    END;
END GET_CATEGORIAS;
/
-- CATEGORIA

CREATE OR REPLACE PROCEDURE GET_CATEGORIA (
    p_id_categoria IN NUMBER,
    p_resultado OUT SYS_REFCURSOR
) IS
    VCOD NUMBER;
    VMES VARCHAR2(500);
BEGIN
    BEGIN

        OPEN p_resultado FOR
        SELECT * FROM categoria
        WHERE ID_CATEGORIA = p_id_categoria;
        
        IF p_resultado%ROWCOUNT = 0 THEN
            
            CLOSE p_resultado;
            OPEN p_resultado FOR
            SELECT NULL AS ID_CATEGORIA, NULL AS NOMBRE, NULL AS ACTIVO FROM DUAL WHERE 1=0;
        END IF;
       
    EXCEPTION
        WHEN OTHERS THEN
            VMES := SQLERRM;
            VCOD := SQLCODE;
            INSERT INTO ERRORES_AUDIT (USUARIO, ORIGEN, FECHA, VERROR)
            VALUES (USER, 'GET_CATEGORIA', SYSDATE, VCOD || ' - ' || VMES);
            RAISE;--permite que el error que se ha registrado en la tabla ERRORES_AUDIT tambi�n se propague
    END;
END GET_CATEGORIA;


 -- Funcion de usuario details service impl
 
CREATE OR REPLACE PROCEDURE Usuario_Service_impl (
    p_username IN VARCHAR2,
    p_password OUT VARCHAR2,
    p_role OUT VARCHAR2
) IS
    v_rol NUMBER;
    v_cod NUMBER;
    v_mes VARCHAR2(500);
BEGIN
    BEGIN
     
        SELECT PASSWORD, id_rol INTO p_password, v_rol
        FROM usuario
        WHERE USERNAME = p_username;

     
        IF v_rol = 1 THEN
            p_role := 'ROLE_ADMIN';
        ELSE
            p_role := 'ROLE_USER';
        END IF;

    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            v_mes := 'Usuario no encontrado: ' || p_username;
            v_cod := -20001;
            INSERT INTO ERRORES_AUDIT VALUES (USER, 'Usuario_Service_impl', SYSDATE, v_cod || ' - ' || v_mes);


        WHEN OTHERS THEN
            v_mes := SQLERRM;
            v_cod := SQLCODE;
            INSERT INTO ERRORES_AUDIT VALUES (USER, 'Usuario_Service_impl', SYSDATE, v_cod || ' - ' || v_mes);

    END;
END Usuario_Service_impl;

--FUNCION PARA CREAR FACTURA
CREATE OR REPLACE FUNCTION CREAR_FACTURA(usu_id NUMBER)  RETURN 
NUMBER IS
    v_id_factura NUMBER;
    VMES VARCHAR2(4000);
    VCOD NUMBER;
BEGIN
        -- Inserta la factura y captura el ID generado
    INSERT INTO factura (id_usuario, fecha)
    VALUES (usu_id, SYSDATE)
    RETURNING id_factura INTO v_id_factura;

    -- Retorna el ID generado
    RETURN v_id_factura;
EXCEPTION    
     WHEN OTHERS THEN  
     VMES := SQLERRM;
     VCOD := SQLCODE;
     INSERT INTO ERRORES_AUDIT VALUES (USER,'CREAR_FACTURA',SYSDATE, VCOD || ' - '|| VMES );
END CREAR_FACTURA;

SELECT CREAR_FACTURA(1) FROM DUAL;

--ACTUALIZAR FACTURA
CREATE OR REPLACE PROCEDURE ACTUALIZAR_FACTURA(fac_id NUMBER,tot NUMBER)
AS
    VMES VARCHAR2(4000);
    VCOD NUMBER;
BEGIN
    UPDATE Factura
    SET total = tot, estado = 1
    WHERE id_factura = fac_id;
    
EXCEPTION    
     WHEN OTHERS THEN  
     VMES := SQLERRM;
     VCOD := SQLCODE;
     INSERT INTO ERRORES_AUDIT VALUES (USER,'ACTUALIZAR_FACTURA',SYSDATE, VCOD || ' - '|| VMES );
END ACTUALIZAR_FACTURA;


--SP PARA CREAR VENTA
CREATE OR REPLACE PROCEDURE INSERTAR_VENTA(fac_id NUMBER,prod_id NUMBER,prec NUMBER,cant NUMBER)
AS
    VMES VARCHAR2(4000);
    VCOD NUMBER;
BEGIN
    INSERT INTO Venta (id_factura, id_producto, precio, cantidad)
    VALUES (fac_id, prod_id,prec, cant);
    
    UPDATE Producto
    SET existencias = existencias-cant
    WHERE id_producto = prod_id;
    
EXCEPTION    
     WHEN OTHERS THEN  
     VMES := SQLERRM;
     VCOD := SQLCODE;
     INSERT INTO ERRORES_AUDIT VALUES (USER,'INSERTAR_VENTA',SYSDATE, VCOD || ' - '|| VMES );
END INSERTAR_VENTA;


CREATE OR REPLACE PROCEDURE CREAR_USUARIO (nomb VARCHAR2,apelli VARCHAR2,mail VARCHAR2,direc VARCHAR2,userna VARCHAR2,pass VARCHAR2,tarj VARCHAR2,pin_us VARCHAR2) AS
BEGIN
        INSERT INTO Usuario (nombre, apellido, correo, direccion, username, password, tarjeta, pin, fecha, activo, id_rol)
        VALUES (nomb, apelli, mail, direc, userna, pass, tarj, pin_us, SYSDATE, 0, 2);

END CREAR_USUARIO;

///GET USUARIO POR US Y PASS
CREATE OR REPLACE PROCEDURE GET_USUARIO_POR_USERNAME_Y_PASSWORD(usern IN VARCHAR2,pass IN VARCHAR2,usu OUT NUMBER,
    nomb OUT VARCHAR2,ape OUT VARCHAR2,corre OUT VARCHAR2,direc OUT VARCHAR2,tarj OUT VARCHAR2,pinn OUT VARCHAR2,
    fech OUT DATE,acti OUT NUMBER,id_rol OUT NUMBER) AS
    
    VMES VARCHAR2(4000);
    VCOD NUMBER;
BEGIN
    SELECT id_usuario, nombre, apellido, correo, direccion, tarjeta, pin, fecha, activo, id_rol
    INTO usu,nomb,ape,corre,direc,tarj,pinn,fech,acti,id_rol
    FROM Usuario
    WHERE username = usern
    AND password = pass;
    
EXCEPTION
     WHEN OTHERS THEN  
     VMES := SQLERRM;
     VCOD := SQLCODE;
     INSERT INTO ERRORES_AUDIT VALUES (USER,'GET_USUARIO_POR_USERNAME_Y_PASSWORD',SYSDATE, VCOD || ' - '|| VMES );      
END GET_USUARIO_POR_USERNAME_Y_PASSWORD;